{
  "Name": "manucorporat/try",
  "Path": "./repositories/manucorporat__try",
  "GoVersion": "n/a",
  "BenchmarkData": {
    "timestamp": "2023-10-26T05:49:07Z",
    "benchmarkCount": 0,
    "benchmarkSuiteCount": 0,
    "successfulBenchmarkCount": 0,
    "successfulBenchmarkSuitesCount": 0,
    "goos": "n/a",
    "goarch": "n/a",
    "suites": []
  },
  "GitRepo": {
    "full_name": "manucorporat/try",
    "name": "try",
    "private": false,
    "html_url": "https://github.com/manucorporat/try",
    "description": "Try/catch/finally in Go. This is an experiment that tries to bring the exception behaviour of java/python/c++ to Golang using the same syntax.",
    "fork": false,
    "created_at": "2014-08-14T18:41:05Z",
    "updated_at": "2023-09-09T02:30:25Z",
    "pushed_at": "2017-06-09T13:42:56Z",
    "ssh_url": "git@github.com:manucorporat/try.git",
    "stargazers_count": 209,
    "watchers_count": 209,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks": 31,
    "language": "Go",
    "archived": false,
    "disabled": false,
    "open_issues": 1,
    "topics": [],
    "allow_forking": true,
    "is_template": false,
    "cloning_error": "",
    "score": 1,
    "license": {
      "key": "",
      "name": "",
      "node_id": "",
      "html_url": ""
    }
  },
  "CodeStatistics": {
    "Count": 2,
    "Lines": 295,
    "Blank": 57,
    "Code": 226,
    "Comment": 12,
    "Bytes": 4783,
    "Complexity": 56
  }
}